### ISSUE TITLE
Publish app on F-Droid

### ISSUE THREAD

**Issue by Ram-Z** [wger-project/flutter#84] opened 2021-09-17 20:27 UTC
## Proposal

Publish wger on F-Droid.

**Comment by rolandgeider** [comment] 2021-09-17 20:42
Hi! Yeah, this is planned, it's just that we need to change some things so that f-droid can build from source (things like moving the fastlane config to the root folder or saving the API keys)

**Comment by Ram-Z** [comment] 2021-09-17 21:50
Anything I can help with? I'm not familiar with flutter or f-droids requirements but happy to read up if pointed at the right places.

**Comment by M123-dev** [comment] 2021-09-18 09:19
We release the app with [fastlane ](https://fastlane.tools/) running on [github actions](https://github.com/features/actions).
You can find the workflow in this repository under [.github/workflows/android-release.yml](https://github.com/wger-project/flutter/blob/4eb1580359f362ddf7920a7bb218c411b2c90adc/.github/workflows/android-release.yml)

You can inform yourself if there are either fastlane plugins or github actions for publishing on F-Droid. From my expierence I would recommend to check if there are github actions for that first since they are easier to work with.

I just did some quick googling myself, I think for F-droid it will be relatively hard to find something.

**Comment by Ram-Z** [comment] 2021-09-18 12:24
Thanks. I'll read up on that.

Been looking into the process of registering f-droid applications [here](https://f-droid.org/en/docs/Inclusion_How-To/#Proposal_by_Metadata_Merge_Request) and [here][https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests), it seems that f-droid will build their own apks to publish on they store. We just need to provide the commands to publish the app.

I've created a new  entry for `wger` in my [fdroiddata fork](https://gitlab.com/Ram-Z/fdroiddata/-/commit/60764fff9cf88ca9934f59b80fb0ce68770de60a#1b312dcbec6bb1433471161331cd5600eb20d846) and been playing around with that a bit.

Furthermore, a few things would make releasing on f-droid a bit easier:
* tagging releases
  * looks like currently you simply create a `release/<version>` branch and trigger the github actions on that, this might need updating to be run on tags instead
* getting f-droid to read metadata from fastlane
  * it seems f-droid only supports these locations for fastlane metadata (see [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure), i guess that's what @rolandgeider mentionned)
    * `metadata/`
    * `fastlane/metadata/android/`
  * if moved, would require updating github actions to be updated to use the new fastlane locations

I'm having a few issues to get the app to actually build on my machine atm. So, I'm going to try to setup the [fdroid build environment](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/#setup), rather than attempt to build it natively.

**Comment by rolandgeider** [comment] 2021-09-19 17:55
Thanks for looking into this!

Yes at the moment the whole process is automated and we only need to push to those branches, but addind some tags shouldn't be a problem. Do you know if fdroid use the builds made by fastlane or is it only for the metadata?

I originally created the fastlane config within the android folder because that's how it was described in [the flutter docs](https://flutter.dev/docs/deployment/cd).

What issues are you having? BTW, there is a bug within one of the packages if you use the newly relased flutter 2.5 it won't compile

**Comment by Ram-Z** [comment] 2021-09-19 23:34
From what I understood fdroid only uses fastlane for metadata, it will use it's own build commands defined in the [metadata.yml](https://gitlab.com/Ram-Z/fdroiddata/-/blob/60764fff9cf88ca9934f59b80fb0ce68770de60a/metadata/de.wger.flutter.yml#L22-25) file. However it might infer those build commands from fastlane, I don't know.

> What issues are you having? BTW, there is a bug within one of the packages if you use the newly relased flutter 2.5 it won't compile

Looks like I am, I've opened https://github.com/wger-project/flutter/issues/85 to keep this thread clean.

**Comment by Ram-Z** [comment] 2021-09-23 19:26
OK, so I've got as far as generating the apk using fdroid's build server. https://gitlab.com/Ram-Z/fdroiddata/-/jobs/1604780724

It failed on verifying that the version in the metadata file and the one in the apk match. 

```
2021-09-20 11:32:00,612 ERROR: Could not build app de.wger.flutter: Unexpected version/version code in output; APK: '0.2.0' / '11',  Expected: '1.2.2' / '0'
```

It seems that the apk version is drawn from [pubspec.yaml#L23](https://github.com/wger-project/flutter/blob/master/pubspec.yaml#L23), which is being modified during the github workflow before publishing.

IMO the updated version should probably be committed to pubspec.yaml before publishing.

I'm confident now that fdroid build server will be able to build and publish this app, I'll start making changes to this repo now to adhere to their requirements.

1. I think we might be able to keep the fastlane folder where it is. Will address that once I've put up the MR on fdroiddata and received guidance from their reviewers.
2. change the github workflow to publish on tags rather than release branches
3. add some mechanism to automatically update the various places the version is written to, pubspec.yaml, maybe others

**Comment by rolandgeider** [comment] 2021-09-23 20:28
That sounds really promising!

At the moment the GitHub actions automatically reads the version code from Google play and increments it by one during build time, but we can simply set it manually in the pubspec.yaml or perhaps even write it back

**Comment by M123-dev** [comment] 2021-09-23 20:39
@Ram-Z, thats sound like great progess and yes exactly, the version in the pubspec. on master  is actually irrelevant, it is overwritten by fastlane cf: https://github.com/wger-project/flutter/blob/master/android/fastlane/Fastfile#L28



The idea was to automate as much as possible. I actually made the workflow design for another project which is also published on the AppStore. But since IOS and Android have a different counting system for the build number and due to permission problems on the main branch we decided against automatically commiting the version.

I'm not familiar with F-Droid, do you have to specify a build number there?
Also where does the expected version 1.2.2/0 come from?

----

I think the simplest solution would be to [automatically create a Github release](https://github.com/openfoodfacts/openfoodfacts-dart/blob/master/.github/workflows/release.yml#L60) from the android workflow (Where tag = app version/branch name). This is then recognized by F-Droid and since Dart is already setup in the the Gitlab workflow to build the app we can modify the pubspec version via [cider](https://pub.dev/packages/cider) before the build process. The only thing missing in this proposal is the build number.

**Comment by rolandgeider** [comment] 2021-09-23 20:44
I like the idea of using releases to trigger the build on f-droid. Cider looks really interesting as well

**Comment by M123-dev** [comment] 2021-09-23 20:51
@rolandgeider now that depends on your preference. We can either start the android workflow by committing to a branch (as it is now) which then creates a Github release to notify F-Droid  or we can start the release workflow by a manually created release, it should make that much of a difference for the automation workflows.

cf: https://github.community/t/how-to-get-just-the-tag-name/16241

**Comment by Ram-Z** [comment] 2021-09-23 21:16
> I'm not familiar with F-Droid, do you have to specify a build number there?
> Also where does the expected version 1.2.2/0 come from?

It's all defined in the [metadata file](https://gitlab.com/Ram-Z/fdroiddata/-/blob/wger/metadata/de.wger.flutter.yml#L15). This was initially generated via `froid import --url <this-repo>`. However it failed to set the version and build number because there are no tags. So I've put them in myself, didn't know what the build number was, so left it at `0`.

There is also `fdroid checkupdates` which will reimport the metadata, probably automatically creating new entries for new tags if [`UpdateCheckMode`](https://f-droid.org/docs/Build_Metadata_Reference/#updatecheckmode) is set accordingly.

----

What exactly was the issue with iOS? From a brief search it just seems that the restrictions on iOS build numbers are just less stringent than the android build codes:
* iOS: the build number must be monotonically increasing within a version number
* android: the build code must be monotonically increasing always

Nothing stopping you from using the android scheme for iOS apps. :shrug:

**Comment by M123-dev** [comment] 2021-09-26 15:22
@Ram-Z 
If I understood this correctly, the problem is that we do not create github releases.

Does F-Droid need a build number or not, when not we could just create a github release with the branch name at the bottom of the release workflow.



------


> What exactly was the issue with iOS

The problem is such that we have a separate workflow for each platform, for reliability and overview reasons. Committing the version did not make any sense, since 

1. The master and release branches in the other project are extra protected which prevents us from committing with the build in actions key. (We would have had to use the REST API).
2. Workflows are not started by commits from bots.


Since we handled it this way, we could also just use the desired version scheme per platform.

**Comment by rolandgeider** [comment] 2021-09-30 14:20
I'm tending towards keeping the current workflow and creating a release, which would trigger an f-droid build. We could write the build version we get from google play with cider back to pubspec.yaml so that f-droid can use that. And since we don't have any workflows for iOS we also don't have that problem.

Can you post the PR here when you open it @Ram-Z ?

**Comment by rolandgeider** [comment] 2021-11-08 15:24
@Ram-Z I've been playing around with the some updated actions. We can now trigger builds when a new tag is set and a new release is created automatically as well. The correct build number and versions are also written back to the pubspec.yaml file, so there's no magic happening and fdroid can use the same files.

I think the only thing left is see if we can leave the fastlane folder were it is or not.

**Comment by Ram-Z** [comment] 2021-11-11 23:51
Sorry, I've had very little time to look into this again.

> We can now trigger builds when a new tag is set and a new release is created automatically as well. The correct build number and versions are also written back to the pubspec.yaml file, so there's no magic happening and fdroid can use the same files.

That's brilliant, the f-droid build server can then pick up those tags and build its package from it.

**Comment by Ram-Z** [comment] 2021-11-12 00:19
Result!

I've managed to build wger on the [fdroid build servers](https://gitlab.com/Ram-Z/fdroiddata/-/jobs/1775208573), the apk is available as [an artefact](https://gitlab.com/Ram-Z/fdroiddata/-/jobs/1775208573/artifacts/browse/tmp/). \o/

Have not tested it yet, time to go to bed now. I'll be away for the weekend but will try to pick this up again after.

**Comment by Ram-Z** [comment] 2021-11-12 00:27
This will have to be addressed somehow though, I suppose, https://gitlab.com/Ram-Z/fdroiddata/-/jobs/1775208573#L2652

```
Wger Api Key not configured. Set it in `app/wger.properties` or in the environment variable `WGER_API_KEY`
```

It seems you have that key setup as some sort of secret in the github worflows. Don't think that'll work for f-droid.

Could the API_KEY be set at runtime by the user? Although I suppose that won't work for the wger.de instance.

I'm not really sure, I don't know exactly how this is all set up.

**Comment by rolandgeider** [comment] 2021-11-12 07:48
That's great, we are so close.

The API key is only needed during registration, I've added a check that opens a browser when the key is not available, then the users can do that manually. It's probably not the best way to do that UX wise, but it's probably better than nothing

**Comment by Ram-Z** [comment] 2021-11-17 10:34
Couldn't install the built apk on my phone because it wasn't signed. Will have to figure out what needs to be done about that.

**Comment by rolandgeider** [comment] 2021-11-17 10:35
yes, one more for the todo. Perhaps the "real" f-droid build process does that automatically?

**Comment by Ram-Z** [comment] 2021-11-20 21:55
Have created the Request for Inclusion MR on fdroid. Let's see what they say. Thanks for your help so far.

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10095

**Comment by rolandgeider** [comment] 2021-11-20 22:13
Awesome! And thank you so much

**Comment by rolandgeider** [comment] 2021-12-13 13:15
Closing here since the PR on fdroid was merged, now we just have to wait till it's available there as well

**Closed by rolandgeider** 2021-12-13 13:15 UTC
Labels: help wanted
