### ISSUE TITLE
Error: MissingRequiredKeysException: Required keys are missing: created

App Version: 1.5.7
Server Version: 2.2.0a3

### ISSUE THREAD

**Issue by bocklucas** [wger-project/flutter#437] opened 2023-10-17 03:19 UTC
## Steps to Reproduce

1. Log into the app (I'm  connected to a self hosted server running on my home assistant instance, addon I'm  running can be found at https://github.com/alexbelgium/hassio-addons
2. Create a new workout with name and days
3. Go to the details page and add a new set
4. Search for a workout

**Expected results:** I should get a list of exercises back

**Actual results:** ![Screenshot_20231016_220351.jpg](https://github.com/wger-project/flutter/assets/22528729/28afbce1-d6d3-4c61-bd55-2988da64d397)

<details>
  <summary>Home Assistant Logs</summary>

```
[17/Oct/2023 03:10:27] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:10:32] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:10:37] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:10:42] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:10:48] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:10:53] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:10:58] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:11:03] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:11:08] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:11:13] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:11:18] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:11:23] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:11:28] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:11:33] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:11:38] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:11:43] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:11:48] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:11:53] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:11:58] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:12:03] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:12:08] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:12:13] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:12:19] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:12:24] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:12:29] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:12:34] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:12:39] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:12:44] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:12:49] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:12:54] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:12:59] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:13:04] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:13:09] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:13:14] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:13:20] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:13:25] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:13:30] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:13:35] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:13:40] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:13:45] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:13:50] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:13:55] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:14:00] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:14:05] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:14:10] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:14:15] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:14:20] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:14:25] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:14:30] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:14:36] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:14:41] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:14:46] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:14:51] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:14:56] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:01] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:06] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:11] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:16] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:21] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:26] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:31] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:36] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:41] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:46] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:51] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:56] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:15:57] "GET /api/v2/exercise/search/?term=bench+press&language=en HTTP/1.0" 200 2698
[17/Oct/2023 03:15:57] "GET /api/v2/exercisebaseinfo/76/ HTTP/1.0" 200 3654
[17/Oct/2023 03:15:57] "GET /api/v2/exercisebaseinfo/73/ HTTP/1.0" 200 4816
[17/Oct/2023 03:15:57] "GET /api/v2/exercisebaseinfo/185/ HTTP/1.0" 200 2988
[17/Oct/2023 03:15:58] "GET /api/v2/exercisebaseinfo/186/ HTTP/1.0" 200 2036
[17/Oct/2023 03:15:58] "GET /api/v2/exercisebaseinfo/598/ HTTP/1.0" 200 1415
[17/Oct/2023 03:15:58] "GET /api/v2/exercisebaseinfo/537/ HTTP/1.0" 200 3763
[17/Oct/2023 03:15:58] "GET /api/v2/exercisebaseinfo/1041/ HTTP/1.0" 200 3128
[17/Oct/2023 03:15:58] "GET /api/v2/exercisebaseinfo/498/ HTTP/1.0" 200 1545
[17/Oct/2023 03:15:58] "GET /api/v2/exercisebaseinfo/539/ HTTP/1.0" 200 3591
[17/Oct/2023 03:15:58] "GET /api/v2/exercisebaseinfo/538/ HTTP/1.0" 200 4459
[17/Oct/2023 03:15:59] "GET /api/v2/exercise/search/?term=bench+press+&language=en HTTP/1.0" 200 1770
[17/Oct/2023 03:15:59] "GET /api/v2/exercisebaseinfo/76/ HTTP/1.0" 200 3654
[17/Oct/2023 03:15:59] "GET /api/v2/exercisebaseinfo/185/ HTTP/1.0" 200 2988
[17/Oct/2023 03:15:59] "GET /api/v2/exercisebaseinfo/186/ HTTP/1.0" 200 2036
[17/Oct/2023 03:15:59] "GET /api/v2/exercisebaseinfo/538/ HTTP/1.0" 200 4459
[17/Oct/2023 03:15:59] "GET /api/v2/exercisebaseinfo/537/ HTTP/1.0" 200 3763
[17/Oct/2023 03:15:59] "GET /api/v2/exercisebaseinfo/539/ HTTP/1.0" 200 3591
[17/Oct/2023 03:16:02] "GET / HTTP/1.0" 302 0
[17/Oct/2023 03:16:02] "GET /api/v2/exercise/search/?term=bench+press+&language=en HTTP/1.0" 200 1770
[17/Oct/2023 03:16:02] "GET /api/v2/exercisebaseinfo/76/ HTTP/1.0" 200 3654
[17/Oct/2023 03:16:02] "GET /api/v2/exercisebaseinfo/185/ HTTP/1.0" 200 2988
[17/Oct/2023 03:16:02] "GET /api/v2/exercisebaseinfo/186/ HTTP/1.0" 200 2036
[17/Oct/2023 03:16:02] "GET /api/v2/exercisebaseinfo/538/ HTTP/1.0" 200 4459
[17/Oct/2023 03:16:02] "GET /api/v2/exercisebaseinfo/537/ HTTP/1.0" 200 3763
[17/Oct/2023 03:16:02] "GET /api/v2/exercisebaseinfo/539/ HTTP/1.0" 200 3591
[17/Oct/2023 03:16:06] "GET /api/v2/exercise/search/?term=bench+press+&language=en HTTP/1.0" 200 1770
[17/Oct/2023 03:16:06] "GET /api/v2/exercisebaseinfo/185/ HTTP/1.0" 200 2988
[17/Oct/2023 03:16:06] "GET /api/v2/exercisebaseinfo/76/ HTTP/1.0" 200 3654
[17/Oct/2023 03:16:06] "GET /api/v2/exercisebaseinfo/538/ HTTP/1.0" 200 4459
[17/Oct/2023 03:16:06] "GET /api/v2/exercisebaseinfo/186/ HTTP/1.0" 200 2036
[17/Oct/2023 03:16:06] "GET /api/v2/exercisebaseinfo/537/ HTTP/1.0" 200 3763
[17/Oct/2023 03:16:06] "GET /api/v2/exercisebaseinfo/539/ HTTP/1.0" 200 3591
[17/Oct/2023 03:16:07] "GET / HTTP/1.0" 302 0
```

</details>

Let me know if more detail is needed, happy to provide it. Thanks!

**Comment by rolandgeider** [comment] 2023-10-17 09:33
mhh, you are right! I'll take a look later today

**Comment by rolandgeider** [comment] 2023-10-17 12:39
can you update the server and see if this keeps happening?

**Comment by bocklucas** [comment] 2023-10-17 14:36
> can you update the server and see if this keeps happening?

Hmm I can try but that addon is out of my control, I could open an issue in that repo though.

**Comment by bocklucas** [comment] 2023-10-17 15:35
> > can you update the server and see if this keeps happening?
> 
> Hmm I can try but that addon is out of my control, I could open an issue in that repo though.

Yeah looks like I'd have to open a ticket in their repo, I'll do that today and post it here

**Comment by rolandgeider** [comment] 2023-10-17 16:15
Great thank you!

Can you tag me as well?

**Comment by bocklucas** [comment] 2023-10-17 17:41
> Great thank you!
> 
> Can you tag me as well?

Absolutely 😁

**Comment by bocklucas** [comment] 2023-10-17 18:11
Took a look at the code prior to making an issue, it appears it's supposed to pull the latest docker image and I saw it was recently updated on docker, clearing my local machine and trying again

**Comment by bocklucas** [comment] 2023-10-17 18:22
> Took a look at the code prior to making an issue, it appears it's supposed to pull the latest docker image and I saw it was recently updated on docker, clearing my local machine and trying again

Hmm still having issues, will have to dig into this in a few hours, the wger code in the addon says it's pulling from the latest wger server docker image but I'm still having that issue so may still have to open a ticket but I'll be sure to tag you regardless

**Comment by rolandgeider** [comment] 2023-10-17 18:24
We merged a PR yesterday that bumped the version to 2.2.0a3, so you should be able to check if it did in fact pull a new image

**Comment by rolandgeider** [comment] 2023-10-17 18:24
I mean 2.2.0a4 😄

**Comment by bocklucas** [comment] 2023-10-17 23:52
Hmmm for the life of me I can not get it to version 2.2.0a4, its on 2.2.0a3
![Screenshot from 2023-10-17 18-52-09](https://github.com/wger-project/flutter/assets/22528729/927d8a04-8786-4282-894d-acf7a4625774)

**Comment by bocklucas** [comment] 2023-10-28 13:13
Hey @rolandgeider , quick update for you, I finally ended up deploying the docker-compose setup on another server instead of using the Home Assistant addon and am now seeing this, are you able to replicate?
![Screenshot_20231028_081122.jpg](https://github.com/wger-project/flutter/assets/22528729/814e4179-9514-4af3-b7fc-ad892b977c72)

**Comment by rolandgeider** [comment] 2023-10-28 14:05
I might have seen this before but could never really reproduce it, does this alway happen to you or only sometimes?

**Comment by bocklucas** [comment] 2023-10-28 17:03
Oh interesting, yeah this is happening all the time

**Comment by bocklucas** [comment] 2023-10-29 16:30
@rolandgeider will this require server side fixes or flutter fixes do you think?

**Comment by rolandgeider** [comment] 2023-10-29 16:55
I'd guess this is a flutter problem, we're probably not handling some corner case properly

**Comment by rolandgeider** [comment] 2023-10-29 16:56
We'll not a corner case for you 😄😄

**Comment by justinkirby** [comment] 2023-11-06 20:56
I just setup a brand new wger instance, using the docker procedure. First login using the mobile app, installed from fdroid, I get this error.

**Comment by bocklucas** [comment] 2023-11-08 03:53
@justinkirby are you able to elaborate what steps you took to rerun sync-exercises?

**Comment by rolandgeider** [comment] 2023-11-08 13:11
@bocklucas you mean manually triggering the sync? You can just do `docker compose exec web python3 manage.py sync-exercises`

**Comment by bocklucas** [comment] 2023-11-08 13:22
> @bocklucas you mean manually triggering the sync? You can just do `docker compose exec web python3 manage.py sync-exercises`

@rolandgeider correct yeah. Ooo awesome, OK I'll try that, not sure how that'll work in the Home Assistant setup but I'll give that a crack, thanks 😀

**Comment by horseDeveloper** [comment] 2023-11-22 06:27
I've used wger.de with my browser for a few days, today I downloaded the app.
I am using the default server with android wger 1.5.6 - downloaded from F-Droid. I'm on Android 13.
I'm getting the same error.

Also, every time I open the app, 
- My weight logs do not appear on mobile. If I add an entry I'm able to pull down (triggering a refresh) - this updates the graph with the logs added from the website.
- My "workout plans" do not appear on mobile. If I add an entry I'm able to pull down (triggering a refresh) - this updates the list with the workouts added from the website. When I press on one of them, it's empty (probably because it can't get the exercises)

**Comment by rolandgeider** [comment] 2023-11-22 06:29
hi! There should be a new version published on fdroid soon (as in it's been built, it just need to show up), can you try it with it once it's available?

**Comment by horseDeveloper** [comment] 2023-11-24 18:08
Quickly tested it, everything seems to work. Workouts come up, you can add exercises, weight logs are displayed. Everything comes up correctly as soon as I open the app, no need to `pull-down-to-refresh` . I just started with wger so I haven't **logged**  any workouts yet, I'm just adding the exercises and testing things out, so I can't tell you anything about that. Good job :)

**Comment by mikekay1** [comment] 2024-01-05 19:35
I am also getting this error, and when I try to sync exercises I get an error saying one of the exercises is too long 200 chars? could someone have contributed one that is blowing everyone's instance up?

![image](https://github.com/wger-project/flutter/assets/52670539/b88cfa8a-6e6e-4ba9-a389-cb9706107be7)

**Comment by mikekay1** [comment] 2024-01-05 19:37
It's so sad, that wger is our only option for this, I honestly feel like this application could be rebuilt ground up. I am a DBA if anyone is interested in forking it. I cant believe there is no self hosted solution for something like this :(

**Comment by rolandgeider** [comment] 2024-01-06 12:08
turns out, we were writing garbage to the alias field, am cleaning it up right now but the sync should work again

**Comment by rolandgeider** [comment] 2024-12-06 09:41
I think this can be closed

**Closed by rolandgeider** 2024-12-06 09:41 UTC
Labels: bug
